package MUSD;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naduni
 */
public class ReportAdding extends javax.swing.JFrame {

    DefaultChecker dc = new DefaultChecker();
    DBLocal db;
    ArrayList<Integer> restrictedList = new ArrayList<Integer>();
    int restricted = 0;
    User user;
    double rowTotal = 0;
    SortedSet<Integer> eqNumberList = new TreeSet<Integer>();
  //  ArrayList<Integer> eqNumberList = new ArrayList<Integer>();

    public void init(DBLocal db, User user) {
        this.db = db;
        this.user = user;
        initTable();
    }

    private void initTable() {
        String array[][] = new String[100][4];

        /* for(int i=0;i<100;i++){
         for(int j=0;j<4;j++){
         array[i][j] = new String();
         }
         }*/
        ArrayList catagoryList = new ArrayList();
        catagoryList = db.selectLocal("equipmentdetails", "name", null);
        Iterator it = catagoryList.iterator();
        int i = 0;
        while (it.hasNext()) {

            String tmpCat = (String) it.next();
            array[i][0] = tmpCat;
            ArrayList equipList = db.selectLocal("equipment", "name", "catagory = '" + tmpCat + "'");
            Iterator itEqu = equipList.iterator();
            Iterator itAmount = db.selectLocal("equipment", "rate", "catagory = '" + tmpCat + "'").iterator();
            i++;
            restrictedList.add(i - 1);
            while (itEqu.hasNext()) {

                String tmpEqu = (String) itEqu.next();
                array[i][0] = tmpEqu;
                
                String tmpAmount = (String) itAmount.next();
                array[i][1] = tmpAmount;
                i++;
            }
            restricted = i - 1;
        }

        DefaultTableModel model = new DefaultTableModel(array, new String[]{
            "Item", "Rate", "No of Units", "Amount"

        }) {
            public boolean isCellEditable(int row, int col) {

                if ((col == 0) || (col == 1) || (col == 3)) {
                    return false;
                }
                if (restrictedList.contains(row)) {
                    return false;
                }
                if (row > restricted) {
                    return false;
                }
                return true;

            }
        };

        jTable1.setModel(model);
        
        ArrayList<String> tax = db.selectLocal("taxdetails", "vat", null);
        double vat = Double.parseDouble((String)tax.get(0));
        tax = db.selectLocal("taxdetails", "nbt", null);
        double nbt = Double.parseDouble((String)tax.get(0));
        
        txtVat.setText(String.valueOf(vat));
        txtNBT.setText(String.valueOf(nbt));

    }

    /**
     * Creates new form ReportAdding
     */
    public void tableChanged(TableModelEvent e) {
        // TODO Auto-generated method stub
        System.out.println(e);
    }

    public ReportAdding() {

        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.setCellSelectionEnabled(true);

        /*ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
         cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
         public void valueChanged(ListSelectionEvent e) {
         String selectedData = null;

         int[] selectedRow = jTable1.getSelectedRows();
         int[] selectedColumns = jTable1.getSelectedColumns();

         for (int i = 0; i < selectedRow.length; i++) {
         for (int j = 0; j < selectedColumns.length; j++) {
         selectedData = (String) jTable1.getValueAt(selectedRow[i], selectedColumns[j]);
         }
         }
         System.out.println("Selected: " + selectedData);
         }

         });
         */
        /**
         *
         * @param e
         */
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCenter = new javax.swing.JTextField();
        txtStamping = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        txtCancelledVarificationNo = new javax.swing.JTextField();
        txtNoOfTraders = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNoOfManufactures = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBranch = new javax.swing.JTextField();
        txtBillNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDailyReportNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDepositAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAssistant = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        txtRowTot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtVat = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNBT = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        dpDate = new org.jdesktop.swingx.JXDatePicker();
        dpDeposit = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MS2");
        setName("frameAdd"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        txtStamping.setName(""); // NOI18N

        txtCancelledVarificationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelledVarificationNoActionPerformed(evt);
            }
        });

        txtAmount.setEnabled(false);

        jLabel2.setText("Date");

        jLabel3.setText("Stamping Center");

        jLabel4.setText("Details of Circuit Stamping");

        jLabel6.setText("Issued varification No.From");

        jLabel7.setText("Cancelled varification No.");

        jLabel8.setText("No. of Traders");

        jLabel9.setText("Amount");

        jLabel10.setText("To");

        txtNoOfManufactures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfManufacturesActionPerformed(evt);
            }
        });

        jLabel11.setText("No. of Manufactures");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Rate", "No of Units", "Amount"
            }
        ));
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Date of Money Deposit");

        jLabel12.setText("Branch");

        jLabel13.setText("Bill No.");

        txtBillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillNoActionPerformed(evt);
            }
        });

        jLabel14.setText("Details of Varification Fees:");

        jLabel15.setText("Daily (M/S/2) No");

        txtDailyReportNo.setName("txtDailyReportNo"); // NOI18N
        txtDailyReportNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDailyReportNoActionPerformed(evt);
            }
        });

        jLabel16.setText("Deposit Amount");

        txtDepositAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositAmountActionPerformed(evt);
            }
        });

        jLabel17.setText("Assistant");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtRowTot.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRowTot.setEnabled(false);

        jLabel18.setText("Row Total");

        jLabel19.setText("VAT");

        txtVat.setEnabled(false);

        jLabel21.setText("NBT");

        txtNBT.setEnabled(false);

        jLabel22.setText("Total");

        txtTot.setEnabled(false);

        dpDate.setFormats(new String[] { "dd-MM-yyyy" });

        dpDeposit.setFormats(new String[] { "dd-MM-yyyy" });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSubmit)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStamping, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDailyReportNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCancelledVarificationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNoOfTraders, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(86, 86, 86)
                                        .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtNoOfManufactures, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(dpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRowTot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtNBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(dpDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel16)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtStamping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtDailyReportNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCancelledVarificationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(txtNoOfTraders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel11))
                                            .addComponent(txtNoOfManufactures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRowTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(txtVat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtNBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit)
                            .addComponent(btnSubmit)
                            .addComponent(btnClear))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCancelledVarificationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelledVarificationNoActionPerformed
    }//GEN-LAST:event_txtCancelledVarificationNoActionPerformed

    private void txtNoOfManufacturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfManufacturesActionPerformed
    }//GEN-LAST:event_txtNoOfManufacturesActionPerformed

    private void txtBillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillNoActionPerformed
    }//GEN-LAST:event_txtBillNoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (txtDailyReportNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Daily Report Number cannot be blank!!!");

        }
        if (txtFrom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Issued Varification Number From cannot be blank!!!");

        }
        if (txtTo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Issued Varification Number To cannot be blank!!!");

        }

        if (txtAssistant.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Assitant cannot be blank!!!");

        } else if (dc.isInt(txtBillNo.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Bill Number is Wrong!!!");

        } else if (dc.isInt(txtDepositAmount.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Deposit Amount is Wrong!!!");

        } else {

            String date = sdf.format(dpDate.getDate());
            Recode rec = new Recode(3, date, "Date");
            Table table = new Table();
            table.addRecode(rec);

            rec = new Recode(3, txtCenter.getText(), "Stamping_Center");
            table.addRecode(rec);

            rec = new Recode(3, this.txtStamping.getText(), "Details_of_the_circuit_stamping");
            table.addRecode(rec);

            rec = new Recode(3, this.txtDailyReportNo.getText(), "ms2No");
            table.addRecode(rec);

            rec = new Recode(3, this.txtFrom.getText(), "Issued_varification_No_From");
            table.addRecode(rec);

            rec = new Recode(3, this.txtTo.getText(), "Issued_varification_No_To");
            table.addRecode(rec);

            rec = new Recode(3, this.txtCancelledVarificationNo.getText(), "Cancelled_varification_No");
            table.addRecode(rec);

            rec = new Recode(0, this.txtNoOfTraders.getText(), "No_of_Traders");
            table.addRecode(rec);

            rec = new Recode(0, this.txtNoOfManufactures.getText(), "No_of_Manufacturers");
            table.addRecode(rec);

            rec = new Recode(2, this.txtAmount.getText(), "Amount");
            table.addRecode(rec);

            rec = new Recode(3, sdf.format(dpDeposit.getDate()), "Date_of_money_deposit");
            table.addRecode(rec);

            rec = new Recode(3, this.txtBranch.getText(), "Branch");
            table.addRecode(rec);

            rec = new Recode(3, this.txtBillNo.getText(), "Bill_No");
            table.addRecode(rec);

            rec = new Recode(2, this.txtDepositAmount.getText(), "Deposit_Amount");
            table.addRecode(rec);

            rec = new Recode(3, this.txtAssistant.getText(), "Assistant");
            table.addRecode(rec);

            // adding the instrument details
            Iterator itEq = eqNumberList.iterator();
            while (itEq.hasNext()) {
                int eqNuber = (Integer) itEq.next();
                String eqId = "EQ0";
                if (eqNuber < 10) {
                    eqId += "0" + String.valueOf(eqNuber);
                } else {
                    eqId += String.valueOf(eqNuber);

                }
                System.out.println((String)jTable1.getValueAt(eqNuber, 2));

                rec = new Recode(0, (String)jTable1.getValueAt(eqNuber, 2), eqId);
                table.addRecode(rec);
            }

            // instrument data added
            db.addLocal(user.getId(), table);
            JOptionPane.showMessageDialog(this, "Your data were successfully added!!!");

        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDailyReportNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDailyReportNoActionPerformed
    }//GEN-LAST:event_txtDailyReportNoActionPerformed

    private void txtDepositAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositAmountActionPerformed
    }//GEN-LAST:event_txtDepositAmountActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //  this.txtDate.setText(null);
        this.txtCenter.setText(null);
        this.txtStamping.setText(null);
        this.txtDailyReportNo.setText(null);
        this.txtFrom.setText(null);
        this.txtTo.setText(null);
        this.txtCancelledVarificationNo.setText(null);
        this.txtNoOfTraders.setText(null);
        this.txtNoOfManufactures.setText(null);
        this.txtAmount.setText(null);
        //  this.txtDateOfMoneyDeposit.setText(null);
        this.txtBranch.setText(null);
        this.txtBillNo.setText(null);
        this.txtDepositAmount.setText(null);
        this.txtAssistant.setText(null);

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        String cmd = evt.getActionCommand();

        if (cmd.equals("EXIT")) {
            int selectedOption = JOptionPane.showConfirmDialog(null, "Do you want to close the window?", "Choose", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged

    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped

    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange

        int row = jTable1.getEditingRow();
        int column = jTable1.getEditingColumn();
        double vatAmount =0;
        double nbtAmount = 0;
        double tot=0;
        try {
            String val = (String) jTable1.getValueAt(row, column);
            if (dc.isInt(val)) {
                // valid cell value entered by the user

                double rate = Double.parseDouble((String) jTable1.getValueAt(row, column - 1));

                double amount = rate * Integer.parseInt(val);
                jTable1.setValueAt(String.valueOf(amount), row, column + 1);
                rowTotal += amount;
                vatAmount = amount*Double.parseDouble(txtVat.getText());
                nbtAmount = amount*Double.parseDouble(txtNBT.getText());
                tot = rowTotal + vatAmount + nbtAmount;
                txtAmount.setText(String.valueOf(tot));
                txtTot.setText(String.valueOf(tot));
                
                txtRowTot.setText(String.valueOf(rowTotal));
                eqNumberList.add(row);

                  //  JOptionPane.showMessageDialog(null, "Incorrect entry");
            } else {
                JOptionPane.showMessageDialog(null, "No of Units is not valied");
                jTable1.setValueAt(null, row, column);
            }
        } catch (Exception e) {

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println("errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new ReportAdding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private org.jdesktop.swingx.JXDatePicker dpDate;
    private org.jdesktop.swingx.JXDatePicker dpDeposit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAssistant;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCancelledVarificationNo;
    private javax.swing.JTextField txtCenter;
    private javax.swing.JTextField txtDailyReportNo;
    private javax.swing.JTextField txtDepositAmount;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtNBT;
    private javax.swing.JTextField txtNoOfManufactures;
    private javax.swing.JTextField txtNoOfTraders;
    private javax.swing.JTextField txtRowTot;
    private javax.swing.JTextField txtStamping;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtVat;
    // End of variables declaration//GEN-END:variables
}
